### ISSUE TITLE
Which Zoom system is this code for?

### ISSUE THREAD

**Issue by guyfawcus** [radicalrendell/zoom_remote#1]
Hi @radicalrendell! I know I'm a bit late to the game here but if you're still around, I was wondering what Zoom recorder this code was used with?

I'm trying to do a similar thing with a Zoom H6 and have put some together some information in @AudunVN's [zoom-h6-remote repo](https://github.com/AudunVN/zoom-h6-remote), mainly in AudunVN/zoom-h6-remote#3.

I'm just trying to gather as much information on all of these remotes as I can.

Thanks!

**Comment by radicalrendell** [comment]
Hi James,


I did my testing on a H4n.


Cheers,
Sean

**Comment by guyfawcus** [comment]
Brilliant! Cheers for the quick reply :+1:
